name:                contraption
version:             0.1.0.0
github:              "nedervold/contraption"
license:             BSD3
author:              "Eric Nedervold"
maintainer:          "nedervoldsoftware@gmail.com"
copyright:           "2022 Eric Nedervold"

extra-source-files:
- README.md
- CHANGELOG.md
- NOTES.txt

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nedervold/contraption#readme>

dependencies:
- base >= 4.7 && < 5
- algebraic-graphs == 0.6.1
- array == 0.5.4.0
- bytestring == 0.10.12.1
- cassava == 0.5.3.0
- containers == 0.6.4.1
- directory == 1.3.6.2
- extra == 1.7.12
- filepath == 1.4.2.1
- lens == 5.0.1
- mtl == 2.2.2
- optparse-applicative == 0.16.1.0
- prettyprinter == 1.7.1
- process == 1.6.13.2
- split == 0.2.3.5
- uniplate == 1.6.13

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# - -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  contraption:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - contraption

tests:
  contraption-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - contraption
    - hspec == 2.8.5
    - tasty == 1.4.2.3
    - tasty-discover == 4.2.4
    - tasty-hspec == 1.2.0.1
    - temporary == 1.3

